/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package login.system;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Rushabh Daxini
 */
public class about extends javax.swing.JFrame {
    public Connection cn=null;
        public Statement st; 
        public InputStream in;
        public Connection conn=null;
        ResultSet rs=null;
        public PreparedStatement pst=null;
        int curRow=0;
        String uname,pword;        
    /**
     * Creates new form about
     */
    public about() {
        initComponents();
        try{
           Class.forName("com.mysql.jdbc.Driver");
            conn =DriverManager.getConnection("jdbc:mysql://localhost:3306/project?zeroDateTimeBehavior=convertToNull", "root", "");
             cn =DriverManager.getConnection("jdbc:mysql://localhost:3306/student?zeroDateTimeBehavior=convertToNull", "root", "");
//JOptionPane.showMessageDialog(null,"Connected");
//return conn;
            }
       catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
//return null;
            }
        fillcombo();
        combo1.setSelectedIndex(-1);
        combo2.setSelectedIndex(-1);
        combo3.setSelectedIndex(-1);
        combo4.setSelectedIndex(-1);
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, 
        size.height/2 - getHeight()/2);
        //this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
    public about(String rn){
        initComponents();
        uname=rn;
      //  pword=ps;
        try{
           Class.forName("com.mysql.jdbc.Driver");
            conn =DriverManager.getConnection("jdbc:mysql://localhost:3306/project?zeroDateTimeBehavior=convertToNull", "root", "");
             cn =DriverManager.getConnection("jdbc:mysql://localhost:3306/student?zeroDateTimeBehavior=convertToNull", "root", "");
//JOptionPane.showMessageDialog(null,"Connected");
//return conn;
            }
       catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
//return null;
            }
        fillcombo();
        combo1.setSelectedIndex(-1);
        combo2.setSelectedIndex(-1);
        combo3.setSelectedIndex(-1);
        combo4.setSelectedIndex(-1);
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, 
        size.height/2 - getHeight()/2);
        //this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        label.setText("Logged in as "+uname);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        choice1 = new java.awt.Choice();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        combo1 = new javax.swing.JComboBox<>();
        combo2 = new javax.swing.JComboBox<>();
        combo3 = new javax.swing.JComboBox<>();
        combo4 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        label = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("Project1");
        jCheckBoxMenuItem1.setBorderPainted(true);

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("Project2");
        jCheckBoxMenuItem2.setBorderPainted(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("About SMS");
        setLocationByPlatform(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Myriad Hebrew", 2, 30)); // NOI18N
        jLabel1.setText("CHOICE  FILLING");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 374, 42));

        jTabbedPane1.setAlignmentX(1.0F);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Project 1", "Project 2", "Project 3", "Project 4", "Project 5", "Project 6" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 11, 223, 170));

        jTabbedPane1.addTab("List", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        combo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo1ActionPerformed(evt);
            }
        });
        jPanel2.add(combo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 17, -1, -1));

        combo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo2ActionPerformed(evt);
            }
        });
        jPanel2.add(combo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 55, -1, -1));

        combo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo3ActionPerformed(evt);
            }
        });
        jPanel2.add(combo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 93, -1, -1));

        combo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo4ActionPerformed(evt);
            }
        });
        jPanel2.add(combo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 131, -1, -1));

        jLabel2.setText("Choice1");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 20, 50, -1));

        jLabel3.setText("Choice2");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 58, 50, -1));

        jLabel4.setText("Chioice3");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 96, 50, -1));

        jLabel5.setText("Choice4");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 134, 50, -1));

        jTabbedPane1.addTab("Choices", jPanel2);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 53, -1, -1));

        submit.setBackground(new java.awt.Color(153, 153, 255));
        submit.setFont(new java.awt.Font("Trajan Pro", 1, 12)); // NOI18N
        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        getContentPane().add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jButton1.setBackground(new java.awt.Color(153, 153, 255));
        jButton1.setFont(new java.awt.Font("Trajan Pro", 1, 12)); // NOI18N
        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 280, -1, -1));

        label.setBackground(new java.awt.Color(51, 51, 255));
        label.setFont(new java.awt.Font("Trajan Pro", 1, 14)); // NOI18N
        label.setForeground(new java.awt.Color(255, 0, 0));
        label.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));
        getContentPane().add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 195, 23));

        jLabel6.setBackground(new java.awt.Color(248, 5, 5));
        jLabel6.setForeground(new java.awt.Color(248, 5, 5));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/system/nu2.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 570, 310));

        jPanel3.setBackground(new java.awt.Color(248, 5, 5));
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void combo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo4ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_combo4ActionPerformed

    private void combo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo2ActionPerformed
        // TODO add your handling code here:
        //combo3.removeAllItems();
        //combo4.removeAllItems();
        //fillcombo7();
    }//GEN-LAST:event_combo2ActionPerformed

    private void combo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo3ActionPerformed
        // TODO add your handling code here:
        //combo4.removeAllItems();
        //fillcombo8();
    }//GEN-LAST:event_combo3ActionPerformed

    private void combo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo1ActionPerformed
        // TODO add your handling code here:
        //fillcombo();
        //combo2.removeAllItems();
        //combo3.removeAllItems();
        //combo4.removeAllItems();
        //fillcombo6();
    }//GEN-LAST:event_combo1ActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        try{
            if(combo1.getSelectedItem()==null||combo2.getSelectedItem()==null||combo3.getSelectedItem()==null||combo4.getSelectedItem()==null){
                JOptionPane.showMessageDialog(null,"Fill all four choices");
            }
            else if(combo1.getSelectedItem()==combo2.getSelectedItem()||combo1.getSelectedItem()==combo3.getSelectedItem()||combo1.getSelectedItem()==combo4.getSelectedItem()||combo2.getSelectedItem()==combo3.getSelectedItem()||combo2.getSelectedItem()==combo4.getSelectedItem()||combo3.getSelectedItem()==combo4.getSelectedItem()){
                JOptionPane.showMessageDialog(null,"No two choice can be same");
            } 
            else{
            String sql="SELECT * FROM student_details WHERE rollnumber=?";
            String sql1="select * from student_details";
            PreparedStatement pst1 = cn.prepareStatement(sql1);
            ResultSet rs=pst1.executeQuery();
            while(rs.next()){
                if(rs.getString("rollnumber")==uname){
                    if(rs.getString("choice1")!=null)
                        JOptionPane.showMessageDialog(null,"You have added your choices once");
                    dispose();
                }
            }
           // pst=cn.prepareStatement(sql);
           
            //pst.setString(1,uname);
             //rs=pst.executeQuery();
           // if(rs.next()){
            //    JOptionPane.showMessageDialog(null,"You have added your choices once");
            //}
           // else {
            String rsq="UPDATE student_details SET choice1=?,choice2=?,choice3=?,choice4=? WHERE rollnumber=?";
                pst=cn.prepareStatement(rsq);
                pst.setString(1, (String) combo1.getSelectedItem());
                pst.setString(2, (String) combo2.getSelectedItem());
                pst.setString(3, (String) combo3.getSelectedItem());
                pst.setString(4, (String) combo4.getSelectedItem());
                pst.setString(5, uname);
                //pst.setString(2, pword);
                //pst.setFloat(3, (float) 7.77);
                
                //pst.executeQuery();
                 int executeUpdate = pst.executeUpdate();
                 System.out.println("Status : "+executeUpdate); 
                JOptionPane.showMessageDialog(null,"Data added sucessfully!");
           // }
            }
        }
        catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_submitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        dispose();
        JOptionPane.showMessageDialog(null, "Logged out");
    }//GEN-LAST:event_jButton1ActionPerformed
    private void fillcombo(){
        DefaultListModel dm=new DefaultListModel();
        try{
        String sql="select * from project_list";
        pst=conn.prepareStatement(sql);
        rs=pst.executeQuery();
        while(rs.next()){
            String str=rs.getString("topic");
            combo1.addItem(str);   
            combo2.addItem(str);
             combo3.addItem(str);
             combo4.addItem(str);
             //jList1.add(rs.getString("topic"));
             dm.addElement(str);
             jList1.setModel(dm);
           /* if(str==combo1.getSelectedItem()){
                continue;
            }
            else{
            combo2.addItem(str);
            }         
            if(str==combo1.getSelectedItem()||str==combo2.getSelectedItem()){
                continue;
            }
            else{
            //jComboBox6.addItem(str);
            combo3.addItem(str);
            //jComboBox8.addItem(str);
            }
            if(str==combo1.getSelectedItem()||str==combo2.getSelectedItem()||str==combo3.getSelectedItem()){
                continue;
            }
            else{
            //jComboBox6.addItem(str);
            //jComboBox7.addItem(str);
            combo4.addItem(str);
            } */            
            }
       
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            }
    }
    /*private void fillcombo6(){
        try{
        String sql="select * from project_list";
        pst=conn.prepareStatement(sql);
        rs=pst.executeQuery();
        while(rs.next()){
            String str=rs.getString("topic");
            //jComboBox5.addItem(str);
            if(str==combo1.getSelectedItem()){
                continue;
            }
            else{
            combo2.addItem(str);
            }         
           }
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            }
    }
     private void fillcombo7(){
        try{
        String sql="select * from project_list";
        pst=conn.prepareStatement(sql);
        rs=pst.executeQuery();
        while(rs.next()){
            String str=rs.getString("topic");
            if(str==combo1.getSelectedItem()||str==combo2.getSelectedItem()){
                continue;
            }
            else{
            //jComboBox6.addItem(str);
            combo3.addItem(str);
            //jComboBox8.addItem(str);
            }
           }
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            }
    }
    private void fillcombo8(){
        try{
        String sql="select * from project_list";
        pst=conn.prepareStatement(sql);
        rs=pst.executeQuery();
        while(rs.next()){
            String str=rs.getString("topic");
            if(str==combo1.getSelectedItem()||str==combo2.getSelectedItem()||str==combo3.getSelectedItem()){
                continue;
            }
            else{
            //jComboBox6.addItem(str);
            //jComboBox7.addItem(str);
            combo4.addItem(str);
            }             
           }
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            }
    }*/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(choice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(choice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(choice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(choice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new about().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Choice choice1;
    private javax.swing.JComboBox<String> combo1;
    private javax.swing.JComboBox<String> combo2;
    private javax.swing.JComboBox<String> combo3;
    private javax.swing.JComboBox<String> combo4;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel label;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables

}
