/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login.system;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Rushabh Daxini
 */
public class Admin extends javax.swing.JFrame {
     public Connection cn;
        public Statement st; 
        public InputStream in;
        public Connection conn=null;
        ResultSet rs=null;
        public PreparedStatement pst=null;
        int curRow=0;
        String uname;
        
    /**
     * Creates new form Admin
     */
    public Admin(String str) {
        initComponents();
        uname=str;
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, 
        size.height/2 - getHeight()/2);
        label.setText("Logged in as "+uname);
        //this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        try{
           Class.forName("com.mysql.jdbc.Driver");
            conn =DriverManager.getConnection("jdbc:mysql://localhost:3306/project?zeroDateTimeBehavior=convertToNull", "root", "");
            //JOptionPane.showMessageDialog(null,"Connected");
//return conn;
            }
       catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
//return null;
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_topic = new javax.swing.JTextField();
        txt_numb = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txt_detail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_lang = new javax.swing.JTextField();
        addppi = new javax.swing.JButton();
        result = new javax.swing.JButton();
        label = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        result1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/system/nu2.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trajan Pro", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Project Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 64, -1, 23));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Trajan Pro", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Students");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 124, 130, -1));
        getContentPane().add(txt_topic, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 151, -1));
        getContentPane().add(txt_numb, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 54, -1));

        jButton1.setBackground(new java.awt.Color(153, 153, 255));
        jButton1.setFont(new java.awt.Font("Trajan Pro", 1, 12)); // NOI18N
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 329, -1, -1));

        jButton2.setBackground(new java.awt.Color(153, 153, 255));
        jButton2.setFont(new java.awt.Font("Trajan Pro", 1, 12)); // NOI18N
        jButton2.setText("RESET");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 329, -1, -1));

        jLabel3.setFont(new java.awt.Font("Trajan Pro", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Description");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 174, 140, 22));
        getContentPane().add(txt_detail, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 151, 61));

        jLabel4.setFont(new java.awt.Font("Trajan Pro", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Programing Language");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 267, -1, 22));
        getContentPane().add(txt_lang, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 151, 30));

        addppi.setBackground(new java.awt.Color(153, 153, 255));
        addppi.setFont(new java.awt.Font("Trajan Pro", 1, 12)); // NOI18N
        addppi.setText("Enter students results");
        addppi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addppiActionPerformed(evt);
            }
        });
        getContentPane().add(addppi, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 13, 264, 31));

        result.setBackground(new java.awt.Color(153, 153, 255));
        result.setFont(new java.awt.Font("Trajan Pro", 1, 12)); // NOI18N
        result.setText("Allocate Projects");
        result.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultActionPerformed(evt);
            }
        });
        getContentPane().add(result, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 264, 31));

        label.setBackground(new java.awt.Color(153, 153, 255));
        label.setFont(new java.awt.Font("Trajan Pro", 1, 18)); // NOI18N
        label.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 329, 329, 22));

        jButton3.setBackground(new java.awt.Color(153, 153, 255));
        jButton3.setFont(new java.awt.Font("Trajan Pro", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 0, 0));
        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 329, -1, -1));

        jLabel6.setFont(new java.awt.Font("Trajan Pro", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Add In Project List");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 23, 329, 22));

        result1.setBackground(new java.awt.Color(153, 153, 255));
        result1.setFont(new java.awt.Font("Trajan Pro", 1, 12)); // NOI18N
        result1.setText("Faculty Page");
        result1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                result1ActionPerformed(evt);
            }
        });
        getContentPane().add(result1, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 48, 264, 31));

        jLabel7.setBackground(new java.awt.Color(153, 153, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/system/nu2.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here: 
        
        try{
            int topics=0;
            String sql_check="select * from project_list";
            pst=conn.prepareStatement(sql_check);
            rs=pst.executeQuery();
            while(rs.next()){
                if(rs.getString("Guide").equals(uname))
                    topics++;
            }
            if(topics>=4){
                JOptionPane.showMessageDialog(null,"A faculty can at most add 4 project titles.");
            }
            else{
                String sql="INSERT INTO project_list(topic,students,detail,language,guide) VALUES(?,?,?,?,?)";
                pst=conn.prepareStatement(sql);
                pst.setString(1,txt_topic.getText());
                pst.setString(2,txt_numb.getText());
                pst.setString(3,txt_detail.getText());
                pst.setString(4,txt_lang.getText());
                pst.setString(5,uname);
                int executeUpdate = pst.executeUpdate();
                 System.out.println("Status : "+executeUpdate); 
                 JOptionPane.showMessageDialog(null,"Data added sucessfully!");
            }
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        txt_topic.setText("");
        txt_numb.setText("");
        txt_detail.setText("");
        txt_lang.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void addppiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addppiActionPerformed
        // TODO add your handling code here:
        add_ppi ap=new add_ppi();
        ap.setVisible(true);
        //dispose();
    }//GEN-LAST:event_addppiActionPerformed

    private void resultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultActionPerformed
        // TODO add your handling code here:
        if(uname.equals("admin")){
        result r=new result();
        r.setVisible(true);
        }
        else
            JOptionPane.showMessageDialog(null, "Not logged in as Admin");
    }//GEN-LAST:event_resultActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:      
        dispose();
        JOptionPane.showMessageDialog(null, "Logged out");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void result1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_result1ActionPerformed
       facultypage fp=new facultypage(uname); 
       fp.setVisible(true);
       
// TODO add your handling code here:
    }//GEN-LAST:event_result1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addppi;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel label;
    private javax.swing.JButton result;
    private javax.swing.JButton result1;
    private javax.swing.JTextField txt_detail;
    private javax.swing.JTextField txt_lang;
    private javax.swing.JTextField txt_numb;
    private javax.swing.JTextField txt_topic;
    // End of variables declaration//GEN-END:variables
}
