/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login.system;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author Rushabh Daxini
 */
public class facultypage extends javax.swing.JFrame {
     public Connection cn=null;
        public Statement st; 
        public InputStream in;
        public Connection conn=null;
        ResultSet rs=null;
        public PreparedStatement pst=null,pst1=null;
        int curRow=0;
        String uname,pword;        
    /**
     * Creates new form
     */
    public facultypage(String fac) {
        initComponents();
        uname=fac;
        try{
           Class.forName("com.mysql.jdbc.Driver");
            //conn =DriverManager.getConnection("jdbc:mysql://localhost:3306/project?zeroDateTimeBehavior=convertToNull", "root", "");
             conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/student?zeroDateTimeBehavior=convertToNull", "root", "");
//JOptionPane.showMessageDialog(null,"Connected");
//return conn;
            }
       catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
//return null;
            }
        filllist();
        fill_combo();
        //combo.setSelectedIndex(-1);
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2,size.height/2 - getHeight()/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        r3 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel10 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        l7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        txt_remark = new javax.swing.JTextField();
        txt_id = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        l8 = new javax.swing.JLabel();
        reset1 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        txt_remark1 = new javax.swing.JTextField();
        txt_id1 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        l9 = new javax.swing.JLabel();
        reset2 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        txt_remark2 = new javax.swing.JTextField();
        txt_id2 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        send = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        combo = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_mail = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        r3.setBackground(new java.awt.Color(255, 255, 255));
        r3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        r3.setToolTipText("");

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jList1.setFont(new java.awt.Font("Trajan Pro", 0, 11)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 358, 201));

        jPanel10.setBackground(new java.awt.Color(255, 153, 102));
        jPanel10.setForeground(new java.awt.Color(255, 153, 102));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 260));

        r3.addTab("Students", jPanel2);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l7.setFont(new java.awt.Font("Trajan Pro", 1, 12)); // NOI18N
        l7.setText("ID");
        jPanel1.add(l7, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 19, 60, 20));

        jLabel1.setFont(new java.awt.Font("Trajan Pro", 1, 12)); // NOI18N
        jLabel1.setText("Remark");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 57, 80, 20));

        jButton1.setBackground(new java.awt.Color(153, 255, 255));
        jButton1.setFont(new java.awt.Font("Trajan Pro", 1, 12)); // NOI18N
        jButton1.setText("Add Remark");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 111, -1, -1));

        reset.setBackground(new java.awt.Color(153, 255, 255));
        reset.setFont(new java.awt.Font("Trajan Pro", 1, 12)); // NOI18N
        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        jPanel1.add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 111, -1, -1));

        jPanel9.setBackground(new java.awt.Color(153, 153, 255));

        txt_remark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_remarkActionPerformed(evt);
            }
        });

        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(149, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_remark, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(94, 94, 94))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_remark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(187, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 260));

        r3.addTab("Review 1", jPanel1);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Trajan Pro", 1, 12)); // NOI18N
        jLabel2.setText("Remark");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 57, 60, 20));

        jButton2.setBackground(new java.awt.Color(153, 255, 255));
        jButton2.setFont(new java.awt.Font("Trajan Pro", 1, 12)); // NOI18N
        jButton2.setText("Add Remark");
        jButton2.setToolTipText("");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 111, -1, -1));

        l8.setFont(new java.awt.Font("Trajan Pro", 1, 12)); // NOI18N
        l8.setText("ID");
        jPanel3.add(l8, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 19, 60, 20));

        reset1.setBackground(new java.awt.Color(153, 255, 255));
        reset1.setFont(new java.awt.Font("Trajan Pro", 1, 12)); // NOI18N
        reset1.setText("Reset");
        reset1.setToolTipText("");
        reset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset1ActionPerformed(evt);
            }
        });
        jPanel3.add(reset1, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 111, -1, -1));

        jPanel8.setBackground(new java.awt.Color(153, 153, 255));

        txt_remark1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_remark1ActionPerformed(evt);
            }
        });

        txt_id1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_id1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(144, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_id1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_remark1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(99, 99, 99))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(txt_id1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_remark1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(186, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 260));

        r3.addTab("Review 2", jPanel3);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Trajan Pro", 1, 12)); // NOI18N
        jLabel3.setText("Remark");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 57, 80, 20));

        jButton3.setBackground(new java.awt.Color(153, 255, 255));
        jButton3.setFont(new java.awt.Font("Trajan Pro", 1, 12)); // NOI18N
        jButton3.setText("Add Remark");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 110, -1, -1));

        l9.setFont(new java.awt.Font("Trajan Pro", 1, 12)); // NOI18N
        l9.setText("ID");
        jPanel4.add(l9, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 19, 60, 20));

        reset2.setBackground(new java.awt.Color(153, 255, 255));
        reset2.setFont(new java.awt.Font("Trajan Pro", 1, 12)); // NOI18N
        reset2.setText("Reset");
        reset2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset2ActionPerformed(evt);
            }
        });
        jPanel4.add(reset2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, -1, -1));

        jPanel7.setBackground(new java.awt.Color(153, 153, 255));

        txt_remark2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_remark2ActionPerformed(evt);
            }
        });

        txt_id2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_id2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(160, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_id2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_remark2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(txt_id2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_remark2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(186, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 260));

        r3.addTab("Review 3", jPanel4);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        send.setBackground(new java.awt.Color(204, 255, 255));
        send.setFont(new java.awt.Font("Trajan Pro", 1, 12)); // NOI18N
        send.setText("Send ");
        send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendActionPerformed(evt);
            }
        });
        jPanel5.add(send, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 224, -1, -1));

        jPanel6.setBackground(new java.awt.Color(102, 255, 255));

        combo.setToolTipText("");
        combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboActionPerformed(evt);
            }
        });

        txt_mail.setColumns(20);
        txt_mail.setRows(5);
        txt_mail.setText("Dear student,\n<<text here>>\n\nProf. \nInstitute of technology,\nNirma University,\nAhemdabad");
        jScrollPane2.setViewportView(txt_mail);

        jLabel4.setFont(new java.awt.Font("Trajan Pro", 1, 12)); // NOI18N
        jLabel4.setText("Roll Number");

        jLabel5.setFont(new java.awt.Font("Trajan Pro", 1, 12)); // NOI18N
        jLabel5.setText("Mail body");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 260));

        r3.addTab("   Mail   ", jPanel5);

        getContentPane().add(r3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        jButton4.setBackground(new java.awt.Color(153, 153, 255));
        jButton4.setFont(new java.awt.Font("Trajan Pro", 1, 12)); // NOI18N
        jButton4.setText("<Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, -1, -1));

        jLabel6.setBackground(new java.awt.Color(255, 0, 0));
        jLabel6.setFont(new java.awt.Font("Trajan Pro", 1, 12)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/system/nu1.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_remark1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_remark1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_remark1ActionPerformed

    private void txt_id1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_id1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_id1ActionPerformed

    private void txt_remarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_remarkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_remarkActionPerformed

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idActionPerformed

    private void txt_id2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_id2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_id2ActionPerformed

    private void txt_remark2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_remark2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_remark2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     String sql_input = "SELECT * FROM student_details";// WHERE rollnumber=?";
        try{
            pst=conn.prepareStatement(sql_input);
            //pst.setString(1,txt_id.getText());
            //pst.setString(2,jPasswordField1.getText());
            rs=pst.executeQuery();
            while(rs.next()){
                if(rs.getString("rollnumber").equals(txt_id.getText().toString())){
                    if(rs.getString("review1")==null){
                        String rsq="UPDATE student_details SET review1=? WHERE rollnumber=?";
                        pst1=conn.prepareStatement(rsq);
                        pst1.setString(1,txt_remark.getText());
                        pst1.setString(2,txt_id.getText());
                        int executeUpdate = pst1.executeUpdate();
                        System.out.println("Status : "+executeUpdate); 
                        JOptionPane.showMessageDialog(null,"Data added sucessfully!");
                    }
                    else    JOptionPane.showMessageDialog(null,"Review 1 remarks are already added for entered roll number");
                }
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         String sql_input = "SELECT * FROM student_details WHERE rollnumber=?";
        try{
            pst=conn.prepareStatement(sql_input);
            pst.setString(1,txt_id1.getText());
            //pst.setString(2,jPasswordField1.getText());
            rs=pst.executeQuery();
            if(rs.next()){
                if(rs.getString("review2")!=null){
                    JOptionPane.showMessageDialog(null, "Review 2 remarks are already added for entered roll number");
                }
                 else if(rs.getString("review2")==null){
                    String rsq="UPDATE student_details SET review2=? WHERE rollnumber=?";
                    pst1=conn.prepareStatement(rsq);
                    pst1.setString(1,txt_remark1.getText());
                    pst1.setString(2,txt_id1.getText());
                     int executeUpdate = pst1.executeUpdate();
                     System.out.println("Status : "+executeUpdate); 
                    JOptionPane.showMessageDialog(null,"Data added sucessfully!");
                }
            }   
            else{
                JOptionPane.showMessageDialog(null, "Wrong rollnumber");
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String sql_input = "SELECT * FROM student_details WHERE rollnumber=?";
        try{
            pst=conn.prepareStatement(sql_input);
            pst.setString(1,txt_id2.getText());
            //pst.setString(2,jPasswordField1.getText());
            rs=pst.executeQuery();
            if(rs.next()){
                if(rs.getString("review3")!=null){
                JOptionPane.showMessageDialog(null, "Review 3 remarks are already added for entered roll number");
                }
                 else if(rs.getString("review3")==null){
                        String rsq="UPDATE student_details SET review3=? WHERE rollnumber=?";
                    pst1=conn.prepareStatement(rsq);
                    pst1.setString(1,txt_remark2.getText());
                    pst1.setString(2,txt_id2.getText());
                     int executeUpdate = pst1.executeUpdate();
                     System.out.println("Status : "+executeUpdate); 
                    JOptionPane.showMessageDialog(null,"Data added sucessfully!");
                }
            } 
            else{
                JOptionPane.showMessageDialog(null, "Wrong rollnumber");
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        txt_id.setText("");
        txt_remark.setText("");
    }//GEN-LAST:event_resetActionPerformed

    private void reset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset1ActionPerformed
        txt_id1.setText("");
        txt_remark1.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_reset1ActionPerformed

    private void reset2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset2ActionPerformed
        txt_id2.setText("");
        txt_remark2.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_reset2ActionPerformed

    private void sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendActionPerformed
        // TODO add your handling code here:
        if(combo.getSelectedItem().equals("All")){
            String sql_input = "SELECT * FROM student_details";// WHERE rollnumber=?";
        try{
            pst=conn.prepareStatement(sql_input);
            //pst.setString(1,txt_id.getText());
            //pst.setString(2,jPasswordField1.getText());
            rs=pst.executeQuery();
            while(rs.next()){
                if(rs.getString("Guide").equals(uname)){
                   try{             
                        String host ="smtp.gmail.com" ;
                        String Tosend=rs.getString("rollnumber");
                        boolean sessionDebug = false;
                        Properties prop = System.getProperties();
                        prop.put("mail.smtp.starttles.enables", "true");
                        prop.put("mail.smtp.host",host);
                        prop.put("mail.smtp.port", "587");
                        prop.put("mail.smtp.auth", "true");
                        prop.put("mail.smtp.starttls.required", "true");
                        Tosend+="@nirmauni.ac.in";
                        
                        java.security.Security.addProvider(new com.sun.net.ssl.internal.ssl.Provider());
                        Session ses= Session.getDefaultInstance(prop,null);
                        ses.setDebug(sessionDebug);
                        Message mes = new MimeMessage(ses);
                        mes.setFrom(new InternetAddress("14rushabhdaxini@gmail.com"));
                        mes.setRecipients(Message.RecipientType.TO,InternetAddress.parse(Tosend));           
                        mes.setSubject("Regarding Your Mini Project");
                        mes.setText(txt_mail.getText()); 
                        Transport transport = ses.getTransport("smtp");
                        transport.connect(host,"14rushabhdaxini@gmail.com","changemerd");
                        transport.sendMessage(mes, mes.getAllRecipients());
                        transport.close();

                        JOptionPane.showMessageDialog(null,"Mail sent");

                    }catch(Exception e){
                        System.out.println(e);
                        JOptionPane.showMessageDialog(null,e);

                    }
                }
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        }
        else{
            try{             
                String host ="smtp.gmail.com" ;
                String Tosend=combo.getSelectedItem().toString();
                boolean sessionDebug = false;
                Properties prop = System.getProperties();
                prop.put("mail.smtp.starttles.enables", "true");
                prop.put("mail.smtp.host",host);
                prop.put("mail.smtp.port", "587");
                prop.put("mail.smtp.auth", "true");
                prop.put("mail.smtp.starttls.required", "true");
                Tosend+="@nirmauni.ac.in";

                java.security.Security.addProvider(new com.sun.net.ssl.internal.ssl.Provider());
                Session ses= Session.getDefaultInstance(prop,null);
                ses.setDebug(sessionDebug);
                Message mes = new MimeMessage(ses);
                mes.setFrom(new InternetAddress("14rushabhdaxini@gmail.com"));
                mes.setRecipients(Message.RecipientType.TO,InternetAddress.parse(Tosend));           
                mes.setSubject("Regarding Your Mini Project");
                mes.setText(txt_mail.getText()); 
                Transport transport = ses.getTransport("smtp");
                transport.connect(host,"14rushabhdaxini@gmail.com","changemerd");
                transport.sendMessage(mes, mes.getAllRecipients());
                transport.close();

                JOptionPane.showMessageDialog(null,"Mail sent");

            }catch(Exception e){
                System.out.println(e);
                JOptionPane.showMessageDialog(null,e);

            }
        }
    }//GEN-LAST:event_sendActionPerformed

    private void comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboActionPerformed
    private void filllist(){
        DefaultListModel dm=new DefaultListModel();
        try{
            String r1,r2,r3;
            String sql="select * from student_details";
            //pst.setString(1,uname);
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            while(rs.next()){
                if(rs.getString("Guide")==null)continue;
                
                if(rs.getString("Guide").equals(uname)){
                    String str=rs.getString("rollnumber");
                    String top=rs.getString("Allocated");
                    
                    if(rs.getString("review1")!=null)
                        r1="review1: ("+rs.getString("review1")+")";//.toString;
                    else r1="review1:"+" (not done)";
                    
                    if(rs.getString("review2")!=null)
                        r2="review2: ("+rs.getString("review2")+")";//.toString;
                    else r2="review2:"+" (not done)";
                    
                    if(rs.getString("review3")!=null)
                        r3="review3: ("+rs.getString("review3")+")";//.toString;
                    else r3="review3:"+" (not done)";
                 
                    dm.addElement(str+"="+top+"||"+r1+"||"+r2+"||"+r3);
                    }
                jList1.setModel(dm);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    private void fill_combo(){
        String roll;// = null;
        String str="select * from student_details";
        try{
            pst=conn.prepareStatement(str);
            rs=pst.executeQuery();
            while(rs.next()){
                if(rs.getString("Guide")==null)continue;
                
                if(rs.getString("Guide").equals(uname)){
                   roll=rs.getString("rollnumber");
                   combo.addItem(roll);
                }
                
            }
            combo.addItem("All");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(facultypage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(facultypage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(facultypage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(facultypage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new facultypage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel l7;
    private javax.swing.JLabel l8;
    private javax.swing.JLabel l9;
    private javax.swing.JTabbedPane r3;
    private javax.swing.JButton reset;
    private javax.swing.JButton reset1;
    private javax.swing.JButton reset2;
    private javax.swing.JButton send;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_id1;
    private javax.swing.JTextField txt_id2;
    private javax.swing.JTextArea txt_mail;
    private javax.swing.JTextField txt_remark;
    private javax.swing.JTextField txt_remark1;
    private javax.swing.JTextField txt_remark2;
    // End of variables declaration//GEN-END:variables
}