/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login.system;
import java.awt.AWTEvent;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.sql.*;
import javax.imageio.ImageIO;
import javax.swing.*;
import java.awt.*;
import java.io.InputStream;
import java.util.Properties;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.Message;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
/**
 *
 * @author Rushabh Daxini
 */
public class faculty_login extends javax.swing.JFrame {
    public Connection cn;
        public Statement st; 
        public InputStream in;
        public Connection conn=null;
        ResultSet rs=null;
        public PreparedStatement pst=null;
        int curRow=0;
    /**
     * Creates new form faculty_login
     */
    public faculty_login() {
        initComponents();
         try{
           Class.forName("com.mysql.jdbc.Driver");
            conn =DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/faculty?zeroDateTimeBehavior=convertToNull", "root", "");
            //JOptionPane.showMessageDialog(null,"Connected");
//return conn;
            }
       catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
//return null;
            }
        Toolkit toolkit = getToolkit();
        Dimension dim = toolkit.getScreenSize();
        setLocation(dim.width/2 - getWidth()/2,dim.height/2 - getHeight()/2);
        //this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_title4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel_username4 = new javax.swing.JLabel();
        jLabel_password4 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        button_login4 = new javax.swing.JButton();
        button_register4 = new javax.swing.JButton();
        button_exit4 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        button_exit1 = new javax.swing.JButton();
        txt_password = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel_title4.setBorder(javax.swing.BorderFactory.createTitledBorder("Login"));
        jPanel_title4.setOpaque(false);
        jPanel_title4.setRequestFocusEnabled(false);
        jPanel_title4.setVerifyInputWhenFocusTarget(false);
        jPanel_title4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 0, 0));
        jLabel2.setFont(new java.awt.Font("Trajan Pro", 1, 12)); // NOI18N
        jLabel2.setText("  FACULTY LOGIN");
        jPanel_title4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 30));

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel_title4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 30));

        jLabel_username4.setBackground(new java.awt.Color(251, 10, 39));
        jLabel_username4.setFont(new java.awt.Font("Trajan Pro", 1, 12)); // NOI18N
        jLabel_username4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_username4.setText("Username  ");
        jPanel_title4.add(jLabel_username4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        jLabel_password4.setFont(new java.awt.Font("Trajan Pro", 1, 12)); // NOI18N
        jLabel_password4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_password4.setText("Password");
        jPanel_title4.add(jLabel_password4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));
        jPanel_title4.add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 135, -1));

        button_login4.setBackground(new java.awt.Color(153, 153, 255));
        button_login4.setFont(new java.awt.Font("Trajan Pro", 1, 12)); // NOI18N
        button_login4.setText("Login");
        button_login4.setToolTipText("Login");
        button_login4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_login4ActionPerformed(evt);
            }
        });
        button_login4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                button_login4KeyPressed(evt);
            }
        });
        jPanel_title4.add(button_login4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        button_register4.setBackground(new java.awt.Color(153, 153, 255));
        button_register4.setFont(new java.awt.Font("Trajan Pro", 1, 12)); // NOI18N
        button_register4.setText("Sign Up");
        button_register4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_register4ActionPerformed(evt);
            }
        });
        jPanel_title4.add(button_register4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, -1, -1));

        button_exit4.setBackground(new java.awt.Color(153, 153, 255));
        button_exit4.setFont(new java.awt.Font("Trajan Pro", 1, 12)); // NOI18N
        button_exit4.setText("Cancel");
        button_exit4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_exit4ActionPerformed(evt);
            }
        });
        jPanel_title4.add(button_exit4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, -1, -1));

        jToggleButton1.setBackground(new java.awt.Color(153, 153, 255));
        jToggleButton1.setFont(new java.awt.Font("Trajan Pro", 1, 12)); // NOI18N
        jToggleButton1.setText("Student Login");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel_title4.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 180, -1));

        button_exit1.setBackground(new java.awt.Color(153, 153, 255));
        button_exit1.setFont(new java.awt.Font("Trajan Pro", 1, 12)); // NOI18N
        button_exit1.setText("Forgot Password ?");
        button_exit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_exit1ActionPerformed(evt);
            }
        });
        jPanel_title4.add(button_exit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 180, -1));
        jPanel_title4.add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 135, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/system/nir.jpg"))); // NOI18N
        jLabel1.setText("FACULTY LOGIN");
        jPanel_title4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 390));

        jLabel3.setFont(new java.awt.Font("Trajan Pro", 1, 30)); // NOI18N
        jLabel3.setText("PROJECT  ALLOCATION  SYSTEM");
        jPanel_title4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_title4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_title4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_login4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_login4ActionPerformed
        // TODO add your handling code here:
        if(txt_username.getText()==null||txt_password.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Wrong suername or password");
        }
        else{
            String sql_input = "SELECT * FROM faculty_details WHERE username=? and password=?";
            try{
                 pst=conn.prepareStatement(sql_input);
                pst.setString(1,txt_username.getText());
                pst.setString(2,txt_password.getText());
                rs=pst.executeQuery();
                if (rs.next()){
                    //about ab= new about();
                    //ab.setVisible(true);
                    Admin ad=new Admin(txt_username.getText());
                    ad.setVisible(true);
                    dispose();
                }
                else{
                    JOptionPane.showMessageDialog(null, "Wrong suername or password");
                }
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_button_login4ActionPerformed

    private void button_login4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_button_login4KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_login4KeyPressed

    private void button_register4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_register4ActionPerformed
      try{

            String sql="SELECT * FROM faculty_details WHERE username=?";
            pst=conn.prepareStatement(sql);
            pst.setString(1,txt_username.getText());
             rs=pst.executeQuery();
            if(rs.next()){
                JOptionPane.showMessageDialog(null,"UserName is taken");
            }
            else {

                String rsq="INSERT INTO faculty_details(username,password) VALUES(?,?)";
                pst=conn.prepareStatement(rsq);
                pst.setString(1,txt_username.getText());
                pst.setString(2,txt_password.getText());
                //pst.executeQuery();
                 int executeUpdate = pst.executeUpdate();
                 System.out.println("Status : "+executeUpdate); 
                 JOptionPane.showMessageDialog(null,"Data added sucessfully!");
                 txt_username.setText("");
                 txt_password.setText("");
            }

        }
        catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null,e);
        }
        // TODO add your handling code here:
        
    }//GEN-LAST:event_button_register4ActionPerformed

    private void button_exit4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_exit4ActionPerformed
        dispose();//System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_button_exit4ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        student_login sl=new student_login();
        sl.setVisible(true);
        dispose();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void button_exit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_exit1ActionPerformed
        // TODO add your handling code here:
        Random rand=new Random();
        int code= rand.nextInt(5555)+1;
        //code for mailing the genrated code
        try{             
            String host ="smtp.gmail.com" ;
            String Tosend=txt_username.getText();
            boolean sessionDebug = false;
            Properties prop = System.getProperties();
            prop.put("mail.smtp.starttles.enables", "true");
            prop.put("mail.smtp.host",host);
            prop.put("mail.smtp.port", "587");
            prop.put("mail.smtp.auth", "true");
            prop.put("mail.smtp.starttls.required", "true");
            Tosend+="@nirmauni.ac.in";
        
            java.security.Security.addProvider(new com.sun.net.ssl.internal.ssl.Provider());
            Session ses= Session.getDefaultInstance(prop,null);
            ses.setDebug(sessionDebug);
            Message mes = new MimeMessage(ses);
            mes.setFrom(new InternetAddress("14rushabhdaxini@gmail.com"));
            mes.setRecipients(Message.RecipientType.TO,InternetAddress.parse(Tosend));
           
            mes.setSubject("Forgot password code");
            mes.setText("Code is"+code); 
            Transport transport = ses.getTransport("smtp");
            transport.connect(host,"14rushabhdaxini@gmail.com","changemerd");
            transport.sendMessage(mes, mes.getAllRecipients());
            transport.close();
            JOptionPane.showMessageDialog(null,"Mail sent");
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        //code for updating student tab;e adding recovery_code field
        String rsq="UPDATE faculty_details SET recovery_code=? WHERE username=?";
        try {
            pst=cn.prepareStatement(rsq);
            pst.setInt(1, code);
            pst.setString(2,txt_username.getText());
        } catch (SQLException ex) {
            Logger.getLogger(student_login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_button_exit1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(faculty_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(faculty_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(faculty_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(faculty_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new faculty_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_exit1;
    private javax.swing.JButton button_exit4;
    private javax.swing.JButton button_login4;
    private javax.swing.JButton button_register4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_password4;
    private javax.swing.JLabel jLabel_username4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_title4;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
