/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login.system;
import java.awt.AWTEvent;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.sql.*;
import javax.imageio.ImageIO;
import javax.swing.*;
import java.awt.*;
import java.io.InputStream;
import java.util.Properties;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.Message;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
/**
 *
 * @author Rushabh Daxini
 */
public class forgot_password extends javax.swing.JFrame {
    public Connection cn;
        public Statement st; 
        public InputStream in;
        public Connection conn=null,conn2=null;
        ResultSet rs=null;
        public PreparedStatement pst=null;
        String uname;
        int page,rcode;
        int curRow=0;
    /**
     * Creates new form forgot_password
     */
    public forgot_password(String user,int pc,int recovery_code) {//page code =1 for student ,2 for faculty
        initComponents();
        uname=user;
        page=pc;
        rcode=recovery_code;
        label.setText("As "+uname);
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            conn =DriverManager.getConnection("jdbc:mysql://localhost:3306/student?zeroDateTimeBehavior=convertToNull", "root", "");
            //conn2 =DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/faculty?zeroDateTimeBehavior=convertToNull", "root", "");
            //JOptionPane.showMessageDialog(null,"Connected");
            //return conn;
            }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            //return null;
            }
        Toolkit toolkit = getToolkit();
        Dimension dim = toolkit.getScreenSize();
        setLocation(dim.width/2 - getWidth()/2,dim.height/2 - getHeight()/2);
        //this.setExtendedState(JFrame.MAXIMIZED_BOTH);    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        code = new javax.swing.JTextField();
        newpass = new javax.swing.JTextField();
        conpass = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        resend = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trajan Pro", 1, 12)); // NOI18N
        jLabel1.setText("Recovery Code");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 56, 150, 22));

        jLabel2.setFont(new java.awt.Font("Trajan Pro", 1, 12)); // NOI18N
        jLabel2.setText("New Password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 107, 150, 27));

        jLabel3.setFont(new java.awt.Font("Trajan Pro", 1, 12)); // NOI18N
        jLabel3.setText("Confirm Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 152, 150, 30));

        code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codeActionPerformed(evt);
            }
        });
        getContentPane().add(code, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 110, 32));
        getContentPane().add(newpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 110, 27));
        getContentPane().add(conpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 110, 30));

        jButton1.setBackground(new java.awt.Color(153, 153, 255));
        jButton1.setFont(new java.awt.Font("Trajan Pro", 1, 12)); // NOI18N
        jButton1.setText("Next");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 213, 150, -1));

        jLabel4.setFont(new java.awt.Font("Trajan Pro", 1, 12)); // NOI18N
        jLabel4.setText("PASSWORD RECOVERY");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 353, 27));

        resend.setBackground(new java.awt.Color(153, 153, 255));
        resend.setFont(new java.awt.Font("Trajan Pro", 1, 12)); // NOI18N
        resend.setText("Resend Code");
        resend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resendActionPerformed(evt);
            }
        });
        getContentPane().add(resend, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 254, 150, -1));

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 30));

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));

        label.setFont(new java.awt.Font("Trajan Pro", 0, 11)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(177, Short.MAX_VALUE)
                .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(183, Short.MAX_VALUE)
                .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 460, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void codeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int ok=1;
        if(code.getText()==null||newpass.getText()==null||conpass.getText()==null){
            JOptionPane.showMessageDialog(null,"Fill all fields!");
            ok=0;
        }
        if(Integer.parseInt(code.getText())==rcode){
            if(newpass.getText()==null||conpass.getText()==null){
                JOptionPane.showMessageDialog(null,"Password Fields can not be empty");
                ok=0;
            }
            if(!(newpass.getText().equals(conpass.getText()))){
                JOptionPane.showMessageDialog(null,"Password Fields should match");
                newpass.setText("");
                conpass.setText("");
                ok=0;
            }
            
            if(page==1&&ok!=0){
                String rsq="UPDATE student_details SET passsword=? WHERE rollnumber=?";
                try {
                    pst=conn.prepareStatement(rsq);
                    pst.setString(1,newpass.getText());
                    pst.setString(2,uname);
                    int executeUpdate = pst.executeUpdate();
                    System.out.println("Status : "+executeUpdate); 
                    JOptionPane.showMessageDialog(null,"Password changed successfully!\n"+"Login again");
                    student_login sl=new student_login();
                    sl.setVisible(true);
                    dispose();
                } catch (SQLException ex) {
                   JOptionPane.showMessageDialog(null,ex);
                    //Logger.getLogger(forgot_password.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else if(page==2&&ok!=0){
                String rsq="UPDATE faculty_details SET password=? WHERE username=?";
                try {
                    pst=conn2.prepareStatement(rsq);
                    pst.setString(1,newpass.getText());
                    pst.setString(2,uname);
                    int executeUpdate = pst.executeUpdate();
                    System.out.println("Status : "+executeUpdate); 
                    JOptionPane.showMessageDialog(null,"Password changed successfully!\n"+"Login again");
                    faculty_login fl=new faculty_login();
                    fl.setVisible(true);
                    dispose();
                } catch (SQLException ex) {
                   JOptionPane.showMessageDialog(null,ex);
                    //Logger.getLogger(forgot_password.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        else{
            JOptionPane.showMessageDialog(null,"Wrong Recovery Code");
            code.setText("");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void resendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resendActionPerformed
        // TODO add your handling code here:
        Random rand=new Random();
        int code= rand.nextInt(5555)+1;
        //code for mailing the genrated code
        try{             
            String host ="smtp.gmail.com" ;
            String Tosend=uname;//txt_username.getText();
            boolean sessionDebug = false;
            Properties prop = System.getProperties();
            prop.put("mail.smtp.starttles.enables", "true");
            prop.put("mail.smtp.host",host);
            prop.put("mail.smtp.port", "587");
            prop.put("mail.smtp.auth", "true");
            prop.put("mail.smtp.starttls.required", "true");
            Tosend+="@nirmauni.ac.in";
        
            java.security.Security.addProvider(new com.sun.net.ssl.internal.ssl.Provider());
            Session ses= Session.getDefaultInstance(prop,null);
            ses.setDebug(sessionDebug);
            Message mes = new MimeMessage(ses);
            mes.setFrom(new InternetAddress("14rushabhdaxini@gmail.com"));
            mes.setRecipients(Message.RecipientType.TO,InternetAddress.parse(Tosend));           
            mes.setSubject("Forgot password code");
            mes.setText("Recovery code is "+code+"\n"+"Change Your password with this code and make sure you are not sharing the code with anyone"); 
            Transport transport = ses.getTransport("smtp");
            transport.connect(host,"14rushabhdaxini@gmail.com","changemerd");
            transport.sendMessage(mes, mes.getAllRecipients());
            transport.close();
        
            JOptionPane.showMessageDialog(null,"Mail sent");
                
        }catch(Exception e){
            System.out.println(e);
            JOptionPane.showMessageDialog(null,e);
            
        }
         forgot_password fp=new forgot_password(uname,1,code);
            fp.setVisible(true);
            dispose();        
    }//GEN-LAST:event_resendActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(forgot_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(forgot_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(forgot_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(forgot_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               //new forgot_password().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField code;
    private javax.swing.JTextField conpass;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel label;
    private javax.swing.JTextField newpass;
    private javax.swing.JButton resend;
    // End of variables declaration//GEN-END:variables
}
