/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login.system;

import java.awt.AWTEvent;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.sql.*;
import javax.imageio.ImageIO;
import javax.swing.*;
import java.awt.*;
import java.io.InputStream;
import java.util.Properties;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.Message;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
/**
 *
 * @author Rushabh Daxini
 */
public class System_Admin extends javax.swing.JFrame {
    public Connection cn;
        public Statement st; 
        public InputStream in;
        public Connection conn=null;
        ResultSet rs=null;
        public PreparedStatement pst=null;
        int curRow=0;
    /**
     * Creates new form System_Admin
     */
    public System_Admin() {

        initComponents();
         try{
           Class.forName("com.mysql.jdbc.Driver");
            conn =DriverManager.getConnection("jdbc:mysql://localhost:3306/student?zeroDateTimeBehavior=convertToNull", "root", "");
            //JOptionPane.showMessageDialog(null,"Connected");
//return conn;
            }
       catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
//return null;
            }
        Toolkit toolkit = getToolkit();
        Dimension dim = toolkit.getScreenSize();
        setLocation(dim.width/2 - getWidth()/2,dim.height/2 - getHeight()/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        branch = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        roll1 = new javax.swing.JTextField();
        roll2 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        branch1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        roll = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        result = new javax.swing.JButton();
        result1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        branch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "16bce", "16bit", "16bee", "16bic", "16bec", "16bme", "16bcl" }));
        jPanel1.add(branch, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 26, -1, -1));

        jLabel1.setText("Branch");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 26, 54, 20));

        jLabel2.setText("Roll");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 64, 54, 20));

        jLabel3.setText("Upto");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 95, 57, 23));

        jButton2.setText("ADD");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 169, -1, -1));
        jPanel1.add(roll1, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 64, 57, -1));
        jPanel1.add(roll2, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 131, 57, -1));

        jPanel4.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, -30, 450, 290));

        jTabbedPane2.addTab("Add", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        branch1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "16bce", "16bit", "16bee", "16bic", "16bec", "16bme", "16bcl" }));
        jPanel2.add(branch1, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 26, -1, -1));

        jLabel4.setText("Branch");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 26, 54, 20));

        jLabel5.setText("Roll");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 64, 54, 20));
        jPanel2.add(roll, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 64, 57, -1));

        jButton1.setText("REMOVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 204, -1, -1));

        jPanel6.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, -30, 450, 290));

        jTabbedPane2.addTab("Delete", jPanel2);

        result.setBackground(new java.awt.Color(153, 153, 255));
        result.setFont(new java.awt.Font("Trajan Pro", 1, 12)); // NOI18N
        result.setText("Allocate Projects");
        result.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultActionPerformed(evt);
            }
        });

        result1.setBackground(new java.awt.Color(153, 153, 255));
        result1.setFont(new java.awt.Font("Trajan Pro", 1, 12)); // NOI18N
        result1.setText("Mail allocated topics");
        result1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                result1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(result1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(result, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(result, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(result1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(131, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Result", jPanel5);

        getContentPane().add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 46, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 0, 0));

        jLabel6.setFont(new java.awt.Font("Trajan Pro", 1, 14)); // NOI18N
        jLabel6.setText("ADMIN");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String rollcode=branch.getSelectedItem().toString();
        String start=rollcode+roll1.getText();
        String end=roll2.getText();
        System.out.println(start+" "+end);
        System.out.println("no"+rollcode+"+"+start);
        try{
                String sql="SELECT * FROM student_details WHERE rollnumber=?";
                pst=conn.prepareStatement(sql);
                pst.setString(1,start);
                rs=pst.executeQuery();
                if(rs.next()){
                    JOptionPane.showMessageDialog(null,"rollnumber is taken");
                }
                else {

                    String rsq="INSERT INTO student_details(rollnumber,passsword) VALUES(?,?)";
                    pst=conn.prepareStatement(rsq);
                    pst.setString(1,start);
                    pst.setString(2,start);
                    //pst.executeQuery();
                     int executeUpdate = pst.executeUpdate();
                     System.out.println("Status : "+executeUpdate); 
                    JOptionPane.showMessageDialog(null,"Data added sucessfully!");
                }

            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
                e.printStackTrace();
               
            }
        /*for(int i=start;i<=end;i++){
            System.out.println(rollcode+i);
            try{
                String sql="SELECT * FROM student_details WHERE rollnumber=?";
                pst=conn.prepareStatement(sql);
                pst.setString(1,rollcode+i);
                rs=pst.executeQuery();
                if(rs.next()){
                    JOptionPane.showMessageDialog(null,"rollnumber is taken");
                }
                else {

                    String rsq="INSERT INTO student_details(rollnumber,passsword) VALUES(?,?)";
                    pst=conn.prepareStatement(rsq);
                    pst.setString(1,rollcode+i);
                    pst.setString(2,rollcode+i);
                    //pst.executeQuery();
                     int executeUpdate = pst.executeUpdate();
                     System.out.println("Status : "+executeUpdate); 
                    JOptionPane.showMessageDialog(null,"Data added sucessfully!");
                }

            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
                e.printStackTrace();
               
            }
        }*/
        try{             
            String host ="smtp.gmail.com" ;
            String Tosend=start;
            boolean sessionDebug = false;
            Properties prop = System.getProperties();
            prop.put("mail.smtp.starttles.enables", "true");
            prop.put("mail.smtp.host",host);
            prop.put("mail.smtp.port", "587");
            prop.put("mail.smtp.auth", "true");
            prop.put("mail.smtp.starttls.required", "true");
            Tosend+="@nirmauni.ac.in";
        
            java.security.Security.addProvider(new com.sun.net.ssl.internal.ssl.Provider());
            Session ses= Session.getDefaultInstance(prop,null);
            ses.setDebug(sessionDebug);
            Message mes = new MimeMessage(ses);
            mes.setFrom(new InternetAddress("14rushabhdaxini@gmail.com"));
            mes.setRecipients(Message.RecipientType.TO,InternetAddress.parse(Tosend));           
            mes.setSubject("Enrolled!");
            mes.setText("Dear student You are enrolled in project allocation system. Use rollnumber as password for first time login."); 
            Transport transport = ses.getTransport("smtp");
            transport.connect(host,"14rushabhdaxini@gmail.com","changemerd");
            transport.sendMessage(mes, mes.getAllRecipients());
            transport.close();
        
            JOptionPane.showMessageDialog(null,"Mail sent");
                
        }catch(Exception e){
            System.out.println(e);
            JOptionPane.showMessageDialog(null,e);
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String rollcode=branch1.getSelectedItem().toString();
        String start=rollcode+roll.getText();
        //String end=roll2.getText();
        //System.out.println(start+" "+end);
        System.out.println("no"+rollcode+"+"+start);
        try{
                String sql="DELETE FROM student_details WHERE rollnumber=?";
                pst=conn.prepareStatement(sql);
                pst.setString(1,start);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null,"Deleted");

            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
                e.printStackTrace();
               
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void resultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultActionPerformed
        // TODO add your handling code here:
       
            result r=new result();
            r.setVisible(true);
    }//GEN-LAST:event_resultActionPerformed

    private void result1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_result1ActionPerformed
        // TODO add your handling code here:
        String sql_input = "SELECT * FROM student_details";// WHERE rollnumber=?";
        try{
            pst=conn.prepareStatement(sql_input);
            //pst.setString(1,txt_id.getText());
            //pst.setString(2,jPasswordField1.getText());
            rs=pst.executeQuery();
            while(rs.next()){
                if(rs.getString("Allocated")!=null){
                   try{             
                        String host ="smtp.gmail.com" ;
                        String Tosend=rs.getString("rollnumber");
                        boolean sessionDebug = false;
                        Properties prop = System.getProperties();
                        prop.put("mail.smtp.starttles.enables", "true");
                        prop.put("mail.smtp.host",host);
                        prop.put("mail.smtp.port", "587");
                        prop.put("mail.smtp.auth", "true");
                        prop.put("mail.smtp.starttls.required", "true");
                        Tosend+="@nirmauni.ac.in";
                        String topic=rs.getString("Allocated");
                        String guide=rs.getString("Guide");
                        java.security.Security.addProvider(new com.sun.net.ssl.internal.ssl.Provider());
                        Session ses= Session.getDefaultInstance(prop,null);
                        ses.setDebug(sessionDebug);
                        Message mes = new MimeMessage(ses);
                        mes.setFrom(new InternetAddress("14rushabhdaxini@gmail.com"));
                        mes.setRecipients(Message.RecipientType.TO,InternetAddress.parse(Tosend));           
                        mes.setSubject("MP Allocated Topic");
                        mes.setText("Dear student You are allocated with topic "+topic+"\n"+"Guide- "+guide); 
                        Transport transport = ses.getTransport("smtp");
                        transport.connect(host,"14rushabhdaxini@gmail.com","changemerd");
                        transport.sendMessage(mes, mes.getAllRecipients());
                        transport.close();

                        JOptionPane.showMessageDialog(null,"Mail sent");

                    }catch(Exception e){
                        System.out.println(e);
                        JOptionPane.showMessageDialog(null,e);

                    }
                }
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_result1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(System_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(System_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(System_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(System_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new System_Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> branch;
    private javax.swing.JComboBox<String> branch1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JButton result;
    private javax.swing.JButton result1;
    private javax.swing.JTextField roll;
    private javax.swing.JTextField roll1;
    private javax.swing.JTextField roll2;
    // End of variables declaration//GEN-END:variables
}
